main_app/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('items/create/', views.ItemCreate.as_view(), name='item_create'),
    path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='item_delete')
]

wishlist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Item(models.Model):
    description = models.TextField(max_length=200)
    quantity = models.IntegerField()

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('home')

main_app/views.py
from django.shortcuts import render
from .models import Item
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic import ListView

class HomeView(ListView):
    model = Item
    template_name = "home.html"

class ItemCreate(CreateView):
    model = Item
    fields = ['description', 'quantity']

class ItemDelete(DeleteView):
    model = Item
    success_url = '/'

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>WishList</title>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>
    

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Wishlist</h1>
    {% if item_list.count == 0 %}
        <h3>No Wish Items Exist</h3><hr>
    {% else %}
        <table class="pure-table pure-table-striped">
            <thead>
                <th>Description</th>
                <th>Quantity</th>
                <th>Delete</th>
            </thead>
            <tbody>
                {% for item in item_list %}    
                    <tr>
                        <td>{{item.description}}</td>
                        <td>{{item.quantity}}</td>
                        <td><a href="{% url 'item_delete' item.id %}">X</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table><hr>
    {% endif %}
    
    <a href="{% url 'item_create' %}" class="pure-button" type="submit">ADD WISH ITEM</a>
{% endblock %}

    

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Item</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ item.description }}</span>?</h4>

  <form class="pure-form" action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="pure-button">
    <a href="{% url 'home' %}">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}
{% block content %}

<h1>Add Wish Item</h1><hr>
<form class="pure-form" action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="ADD ITEM" class="pure-button">
</form>

{% endblock %}